version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=enerBit_orders
      - POSTGRES_USER=enerBit
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

  redis:
    image: "redis:alpine"
    # The Command will make redis-server run with our custom Configuration
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass enerBit
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data #Used for persisting data